/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problem1;

/**
 * Custom JFrame Window
 * 
 * @author Evan
 */
public class converterWindow extends javax.swing.JFrame {

    String inputString; //The string that is input by the user, used in both conversions
    String binOutput; //The output string in the decimal to binary conversion
    String decOutput; //The output string in the binary to decimal conversion
    /**
     * Creates new form converterWindow
     */
    public converterWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        decimalInput = new javax.swing.JTextField();
        decimalToBinaryButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        binaryOutput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        binaryInput = new javax.swing.JTextField();
        binaryToDecinalButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        decimalOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Binary/Decimal Converter");

        jLabel2.setText("Decimal");

        decimalToBinaryButton.setText("CONVERT");
        decimalToBinaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalToBinaryButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Binary");

        binaryOutput.setEditable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Binary/Decimal Conversions");
        jLabel1.setOpaque(true);

        jLabel5.setText("Binary");

        binaryToDecinalButton.setText("CONVERT");
        binaryToDecinalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binaryToDecinalButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Decimal");

        decimalOutput.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(binaryOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(decimalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(binaryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(decimalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(decimalToBinaryButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(binaryToDecinalButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(decimalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(decimalToBinaryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(binaryOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(binaryInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(binaryToDecinalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(decimalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Runs when the button to convert a decimal number to binary is pressed
     * 
     * @param evt The event of the button being pressed
     */
    private void decimalToBinaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalToBinaryButtonActionPerformed
        inputString = decimalInput.getText(); //Gets the decimal input as a string
        if (inputString.equals("")) //If there is no input, do nothing
        {
            return;
        }
        int decInput; //Declare an integer value
        try //If the input string is not a number, output an error
        {
            decInput = Integer.parseInt(inputString);
        }
        catch (NumberFormatException ex)
        {
            binaryOutput.setText("Invalid input");
            return;
        }
        if (decInput < 0 || decInput > 255) //If the number is out of range, output an error
        {
            binaryOutput.setText("Out of range");
            return;
        }
        binOutput = Problem1.decimalToBinary(inputString); //Get the binary output
        binaryOutput.setText(binOutput); //Print the binary output
    }//GEN-LAST:event_decimalToBinaryButtonActionPerformed

    /**
     * Runs when the button to convert a binary number to decimal is pressed
     * 
     * @param evt The event of the button being pressed
     */
    private void binaryToDecinalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binaryToDecinalButtonActionPerformed
        inputString = binaryInput.getText(); //Gets the binary input
        if (inputString.equals("")) //If there is no input, do nothing
        {
            return;
        }
        for (int i = 0; i < inputString.length(); i++) //If the input has characters other than '0' or '1', output an error
        {
            if (inputString.charAt(i) != '0' && inputString.charAt(i) != '1')
            {
                decimalOutput.setText("Invalid input");
                return;
            }
        }
        if (inputString.length() > 8) //If the input has more than 8 characters, output an error
        {
            decimalOutput.setText("Out of range");
            return;
        }
        while (inputString.length() < 8) //If the input has less then 8 characters, add 0s to the beginning of the string until there are 8 characters
        {
            inputString = "0" + inputString;
        }
        decOutput = Problem1.binaryToDecimal(inputString); //Get the decimal output
        decimalOutput.setText(decOutput); //Print the decimal output
    }//GEN-LAST:event_binaryToDecinalButtonActionPerformed

    /**
     * Main method
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(converterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(converterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(converterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(converterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new converterWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField binaryInput;
    private javax.swing.JTextField binaryOutput;
    private javax.swing.JButton binaryToDecinalButton;
    private javax.swing.JTextField decimalInput;
    private javax.swing.JTextField decimalOutput;
    private javax.swing.JButton decimalToBinaryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
