/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problem5;
/**
 * Custom JFrame window
 * 
 * @author Evan
 */
public class SurveyForm extends javax.swing.JFrame {

    /**
     * Creates new form SurveyForm
     */
    public SurveyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ShootersCheckBox = new javax.swing.JCheckBox();
        FightersCheckBox = new javax.swing.JCheckBox();
        RPGCheckBox = new javax.swing.JCheckBox();
        PuzzleCheckBox = new javax.swing.JCheckBox();
        PlatformersCheckBox = new javax.swing.JCheckBox();
        SportsCheckBox = new javax.swing.JCheckBox();
        OtherCheckBox = new javax.swing.JCheckBox();
        ArcadeCheckBox = new javax.swing.JCheckBox();
        StrategyCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        q2ComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        q3TextField = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please answer the following survey.");

        jLabel2.setText("1. What types of games do you like? (Check all that apply)");

        ShootersCheckBox.setText("Shooters");

        FightersCheckBox.setText("Fighters");

        RPGCheckBox.setText("RPG");

        PuzzleCheckBox.setText("Puzzle");

        PlatformersCheckBox.setText("Platformers");

        SportsCheckBox.setText("Sports");

        OtherCheckBox.setText("Other");

        ArcadeCheckBox.setText("Arcade");

        StrategyCheckBox.setText("Strategy");

        jLabel3.setText("2. How many hours per week do you spend gaming?");

        q2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<5 hours", "<10 hours", "<15 hours", "15+ hours" }));

        jLabel4.setText("3. Enter a few games you're playing right now (separated by commas)");

        SubmitButton.setText("SUBMIT");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(q2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(q3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FightersCheckBox)
                                            .addComponent(ShootersCheckBox))
                                        .addGap(18, 18, 18))
                                    .addComponent(PlatformersCheckBox))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StrategyCheckBox)
                                    .addComponent(RPGCheckBox)
                                    .addComponent(PuzzleCheckBox))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ArcadeCheckBox)
                                    .addComponent(SportsCheckBox)
                                    .addComponent(OtherCheckBox))
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShootersCheckBox)
                    .addComponent(ArcadeCheckBox)
                    .addComponent(StrategyCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SportsCheckBox)
                    .addComponent(RPGCheckBox)
                    .addComponent(FightersCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PuzzleCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(OtherCheckBox)
                        .addComponent(PlatformersCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(q2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addComponent(q3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Runs when the button to submit your survey results is pressed
     * 
     * @param evt The event of the button being pressed
     */
    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        Survey survey = Survey.readFile();
        survey = UpdateResults(survey);
        survey.writeFile();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * Updates the survey object's results with the current results
     * 
     * @param survey The survey object before updating
     * @return The survey object after updating
     */
    private Survey UpdateResults(Survey survey)
    {
        survey.numSurveys++; //Adds 1 to the number of surveys completed
        
        if (ShootersCheckBox.isSelected()) //Adds 1 to the tally of any options in question 1 that are checked
        {
            survey.q1Numbers[0]++;
        }
        if (FightersCheckBox.isSelected())
        {
            survey.q1Numbers[1]++;
        }
        if (PlatformersCheckBox.isSelected())
        {
            survey.q1Numbers[2]++;
        }
        if (StrategyCheckBox.isSelected())
        {
            survey.q1Numbers[3]++;
        }
        if (RPGCheckBox.isSelected())
        {
            survey.q1Numbers[4]++;
        }
        if (PuzzleCheckBox.isSelected())
        {
            survey.q1Numbers[5]++;
        }
        if (ArcadeCheckBox.isSelected())
        {
            survey.q1Numbers[6]++;
        }
        if (SportsCheckBox.isSelected())
        {
            survey.q1Numbers[7]++;
        }
        if (OtherCheckBox.isSelected())
        {
            survey.q1Numbers[8]++;
        }
        
        for (int i = 0; i < 4; i++) //Adds one to the tally of the option in question 2 that is chosen
        {
            if (q2ComboBox.getSelectedItem() == survey.q2Names[i])
            {
                survey.q2Numbers[i]++;
            }
        }
        
        survey.q3Answers = Survey.addString(survey.q3Answers, q3TextField.getText()); //Adds the user's answer to question 3 to the array
        return survey;
    }
    /**
     * Main method
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurveyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurveyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurveyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurveyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SurveyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ArcadeCheckBox;
    private javax.swing.JCheckBox FightersCheckBox;
    private javax.swing.JCheckBox OtherCheckBox;
    private javax.swing.JCheckBox PlatformersCheckBox;
    private javax.swing.JCheckBox PuzzleCheckBox;
    private javax.swing.JCheckBox RPGCheckBox;
    private javax.swing.JCheckBox ShootersCheckBox;
    private javax.swing.JCheckBox SportsCheckBox;
    private javax.swing.JCheckBox StrategyCheckBox;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> q2ComboBox;
    private javax.swing.JTextField q3TextField;
    // End of variables declaration//GEN-END:variables
}
